-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 14:18:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema manimals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manimals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manimals` DEFAULT CHARACTER SET utf8 ;
USE `manimals` ;

-- -----------------------------------------------------
-- Table `manimals`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR(200) NOT NULL,
  `telefone` CHAR(200) NOT NULL,
  `email` CHAR(200) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `senha` CHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manimals`.`kind`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`kind` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manimals`.`breeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`breeds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR(200) NOT NULL,
  `kind_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_breeds_kind1`
    FOREIGN KEY (`kind_id`)
    REFERENCES `manimals`.`kind` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-----------------------
-- Table `manimals`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_breed` INT NOT NULL,
  `pet_name` CHAR(200) NOT NULL,
  `birthday` DATE NOT NULL,
  `localizacao` CHAR(200) NOT NULL,
  `nickname` CHAR(200) NULL,
  `bio` TEXT NULL,
  `photo_profile` CHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `manimals`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_breeds1`
    FOREIGN KEY (`id_breed`)
    REFERENCES `manimals`.`breeds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

----------------------------
-- Table `manimals`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `qtd_fotos` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_album_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------
-- Table `manimals`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `post` TEXT NOT NULL,
  `link` CHAR(255) NULL,
  `likes` INT NOT NULL,
  `qtd_comentarios` INT NOT NULL,
  `share` INT NOT NULL,
  `photo` CHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-------------------------
-- Table `manimals`.`photos_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`photos_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_album` INT NULL,
  `id_post` INT NULL,
  `photo` CHAR(200) NOT NULL,
  `fotos_tipo` CHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_photos_content_album1`
    FOREIGN KEY (`id_album`)
    REFERENCES `manimals`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photos_content_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `manimals`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------------------
-- Table `manimals`.`new_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`new_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `nome_evento` CHAR(200) NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `hora_inicial` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `dia_todo` TINYINT(1) NULL,
  `local` CHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `data_criacao` DATE NOT NULL,
  `foto_capa` CHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_new_event_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-----------------------------------
-- Table `manimals`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_new_event` INT NOT NULL,
  `name` CHAR(255) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `localizacao` CHAR(255) NOT NULL,
  `qtd_comentarios` INT NOT NULL,
  `likes` INT NOT NULL,
  `share` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_new_event1`
    FOREIGN KEY (`id_new_event`)
    REFERENCES `manimals`.`new_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-------------------------------
-- Table `manimals`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `status` CHAR(200) NOT NULL,
  `data_relacionamento` DATE NOT NULL,
  `data_atualizacao` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_friends_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-------------------------------
-- Table `manimals`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manimals`.`share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_share_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------
-- Table `manimals`.`perfil_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`perfil_has_evento` (
  `perfil_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`perfil_id`, `evento_id`),
  CONSTRAINT `fk_perfil_has_evento_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_has_evento_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `manimals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-------------------------------------------------
-- Table `manimals`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_likes_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------
-- Table `manimals`.`convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`convite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notificacoes_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manimals`.`profile_has_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`profile_has_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `id_comment` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_has_comments1_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_comments1_comments1`
    FOREIGN KEY (`id_comment`)
    REFERENCES `manimals`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `manimals`.`likes_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`likes_has_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_like` INT NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_likes_has_event_likes1`
    FOREIGN KEY (`id_like`)
    REFERENCES `manimals`.`likes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_has_event_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `manimals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

------------------------------------------
-- Table `manimals`.`comments_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`comments_has_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_comment` INT NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_has_event_comments1`
    FOREIGN KEY (`id_comment`)
    REFERENCES `manimals`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_has_event_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `manimals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

 -----------------------------------------------------
-- Table `manimals`.`profile_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`profile_has_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_has_event_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `manimals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------------------------------
-- Table `manimals`.`event_has_share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`event_has_share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_event` INT NOT NULL,
  `id_share` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_has_share_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `manimals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_share_share1`
    FOREIGN KEY (`id_share`)
    REFERENCES `manimals`.`share` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-------------------------------------------
-- Table `manimals`.`post_has_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`post_has_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_likes` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_has_likes_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `manimals`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_likes_likes1`
    FOREIGN KEY (`id_likes`)
    REFERENCES `manimals`.`likes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------------------
-- Table `manimals`.`profile_has_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`profile_has_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `id_comment` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_has_comments1_profile1`
    FOREIGN KEY (`id_profile`)
    REFERENCES `manimals`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_comments1_comments1`
    FOREIGN KEY (`id_comment`)
    REFERENCES `manimals`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `manimals`.`post_has_share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`post_has_share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_share` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_has_share_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `manimals`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_share_share1`
    FOREIGN KEY (`id_share`)
    REFERENCES `manimals`.`share` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

---------------------------------------
-- Table `manimals`.`post_has_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manimals`.`post_has_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_has_comments_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `manimals`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_comments_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `manimals`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


